# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 684534be67498305aca7f794b858aef963914d856a9914a3eb588cf653a6ba51a9b1cb8fb93a08f91efafc7cf2c2d8f60ef6e10fbb918296a3d778ddc78dc462
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 3d98b3bbb6b5b3b5df6a3787a89e06c7c3f114fa80db22820d00fe84eb7173e2ea716d5dccd5d617648db9f97f5b70c5b8126690fa367693e797fb5d32ad6942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
